ci: 🦀 rework the ci workflow
see [ENG-469]. this provides a new `ci.yml` file, using GitHub's
provided starter sample.

locally, i could not compile `banyan-task` using the flags specified in
ci.yml:

```
Compiling banyan-task v0.1.0 (/home/overx/banyan/banyan-core/crates/banyan-task)
error: can't instrument with gcov profiling when compiling incrementally

error: could not compile `banyan-task` (lib) due to 1 previous error
```

in ci, we see thousands of lines like this:

```
( profiling: /home/runner/work/banyan-core/banyan-core/target/debug/deps/regex_automata-22431596656e6029.gcda: cannot merge previous GCDA file: corrupt arc tag (0x28fb4b04)
profiling: /home/runner/work/banyan-core/banyan-core/target/debug/deps/regex_automata-22431596656e6029.gcda: cannot merge previous GCDA file: corrupt arc tag (0x01000000)
profiling: /home/runner/work/banyan-core/banyan-core/target/debug/deps/regex_automata-22431596656e6029.gcda: cannot merge previous GCDA file: corrupt arc tag (0x00000002)
```

while investigating this further, i found that the
[action-rs/cargo][action-rs] action has been archived since 2023/10/13.
we should move to something else.

additionally, because we are no longer using code coverage, we
move over to the stable toolchain.

[action-rs]: https://github.com/actions-rs/cargo
[ENG-469]: https://linear.app/banyan/issue/ENG-469/investigate-ci-blockage